-- KAIST 장학금 — 하네스 자동 수집 초안 (2026-08-16)
-- 사람 리뷰 후 이 내용을 supabase/data_kaist.sql로 옮길 것.
-- 실제 DB 반영은 지금처럼 supabase/tools/run_sql.py를 사람이 직접 실행함 — 이 파일은 초안임.
-- needs_review로 플래그된 필드가 있는 행은 같은 이름의 harness_review_*.md에서 근거를 먼저 확인할 것.

INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, required_disability_type, foreigner_eligibility, language_test_type, language_test_min_score, required_special_status, required_special_status_all, excluded_special_status, application_deadline, grade_level, major, excluded_major, admission_track, affiliated_institution, min_credits, min_credits_last_semester, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('신세계그룹 ''리테일 All-in-One 교육 과정 2기'' 교육생 모집', '신세계그룹', '교육부터 취업까지, 상위 5% 채용. 신세계그룹과 함께하는 리테일 All-in-One 교육 과정 모집. 오프라인 리테일, F&B, 호텔·서비스, 리테일테크까지 다양한 산업 영역을 한 과정에서 경험할 수 있음. 교육혜택: 1. 우수 교육생 채용 연계 - 상위 5% 채용, 차상위 10% 서류전형 면제(이마트, 조선호텔앤리조트, 신세계푸드, 신세계아이앤씨) 2. 교육비 전액 지원 및 교육지원금 지급 - 교육비 전액(중식 포함), 교육지원금(50만원/월) 3. 체계적인 취업 지원 프로그램 운영 - 합숙 취업캠프, 진로 멘토링, 기업 설명회 등. 교육기간: [2기] 2026.09.09(수) ~ 2026.12.02.(수). 교육장소: 천안(서북구), 대전(서구), 대구(동구), 부산(금정구, 해운대구), 광주(남구)', 500000, 'https://futurendreamacademy.com/', 15, 34, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-08-18', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[2기] 2026.06.18(목) ~ 2026.08.18.(화), 17시까지', NULL, NULL, NULL, NULL, NULL, NULL, 'support_fund', 'activity_participation_support'),
('Merck International Graduate Fellowship - 2027년 장학생 모집', 'Merck', '분야는 총 두가지로 Next Generation Biology와 Sustainability이며, 각 분야별 2명을 모집하여 정원이 작년에 비해 2배로 확대되었습니다. 저년차 대상으로 모집하여 성과중심이 아닌 잠재력 위주로 평가하여 장학생을 선발할 예정이라고 합니다. 선정된 연구자는 최대 3년간 매년 €16,000(최대 한화 8,300만원 상당)의 장학금을 받을 수 있습니다.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, '저년차 대상으로 모집', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '각 분야별 2명 (총 4명)', '지원 기한은 7월 20일까지', NULL, NULL, 'post_undergrad', NULL, NULL, NULL, 'school_external', 'private_foundation'),
('2026년 미원상사 두명장학생(추가) 선발', '미원상사', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, '신소재공학과', NULL, NULL, NULL, NULL, NULL, 'KAIST', NULL, NULL, NULL, NULL, NULL, 'school_external', 'private_foundation'),
('KAIST-EPSD 장학생 (삼성디스플레이)', '삼성디스플레이', '삼성디스플레이 인재양성 프로그램(EPSD)으로, KAIST와 협력하여 산학교육 프로그램을 운영하며 학부 기졸업자 및 졸업예정자를 대상으로 장학생을 모집함', NULL, 'https://epsd.kaist.ac.kr/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-07-08', '학부 기졸업자, 2027년 2월 졸업 예정자', NULL, NULL, 'general', NULL, NULL, NULL, NULL, NULL, '2026. 6. 29(금) 10:00 ~ 7.8(수) 17:30', 'KAIST', NULL, 'post_undergrad', NULL, NULL, NULL, 'school_external', 'private_foundation'),
('삼성디스플레이 KAIST-EPSD 장학생 구분변경 신청', '삼성디스플레이', '삼성디스플레이 KAIST-EPSD(Educational Program for Samsung Display, 삼성디스플레이 인재양성 프로그램) 장학생의 구분변경 신청 안내. 학교 산학프로그램 사무국에서 발송한 ''KAIST 장학생 구분변경 신청'' 안내 메일을 확인한 후, 신청서를 작성하여 EPSD 사무국으로 제출.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-07-08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026. 7.1(수) ~ 7.8(수)', 'KAIST', NULL, 'post_undergrad', NULL, NULL, NULL, 'school_external', 'private_foundation'),
('삼성디스플레이-KAIST EPSD 구분변경 장학생 모집', '삼성디스플레이', '삼성디스플레이-KAIST EPSD 구분변경 장학생 모집 관련 공고. 첨부파일(삼성디스플레이 EPSD 구분변경 장학생 모집.png)에 세부 내용이 있으나 본문 텍스트에는 상세 자격조건이 제시되어 있지 않음.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-04-10', NULL, '신소재공학과', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~4/10', 'KAIST', NULL, NULL, NULL, NULL, NULL, 'school_external', 'private_foundation'),
('신세계그룹과 함께하는 리테일 All-in-One 교육 과정', '신세계그룹', '미취업 청년 대상 리테일 분야 교육 과정으로, 우수 교육생 채용 연계(상위 5% 채용, 차상위 10% 서류전형 면제), 교육비 전액 지원 및 교육지원금(50만원/월) 지급, 취업 지원 프로그램(합숙 취업캠프, 진로 멘토링, 기업 설명회 등)을 제공함. 교육장소는 천안(서북구), 대전(동구), 대구(동구), 부산(금정구, 해운대구, 연제구), 광주(남구).', NULL, 'https://futurendreamacademy.com/', 15, 34, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[1기] 2026.06.18(목) ~ 2026.07.13(월), 17시까지 / [2기] 2026.06.18(목) ~ 2026.08.18(화), 17시까지', NULL, NULL, NULL, NULL, NULL, NULL, 'support_fund', 'activity_participation_support'),
('삼성디스플레이 EPSD 장학생', '삼성디스플레이', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3.27(금)~4.7(화)', 'KAIST', NULL, NULL, NULL, NULL, NULL, 'school_external', 'private_foundation'),
('신세계그룹 ''리테일 All-in-One 교육 과정 2기'' 교육생 모집', '신세계그룹', '교육부터 취업까지, 상위 5% 채용. 오프라인 리테일, F&B, 호텔·서비스, 리테일테크까지 다양한 산업 영역을 한 과정에서 경험. 우수 교육생 채용 연계(상위 5% 채용, 차상위 10% 서류전형 면제 - 이마트, 조선호텔앤리조트, 신세계푸드, 신세계아이앤씨), 교육비 전액 지원 및 교육지원금 지급(교육비 전액(중식 포함), 교육지원금 50만원/월), 체계적인 취업 지원 프로그램(합숙 취업캠프, 진로 멘토링, 기업 설명회 등). 교육장소: 천안(서북구), 대전(서구), 대구(동구), 부산(금정구, 해운대구), 광주(남구). 교육기간: 2026.09.09(수) ~ 2026.12.02(수)', NULL, 'https://futurendreamacademy.com/', 15, 34, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-08-18', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026.06.18(목) ~ 2026.08.18.(화), 17시까지', NULL, NULL, NULL, NULL, NULL, NULL, 'support_fund', 'activity_participation_support'),
('리테일 All-in-One 교육 과정 2기', '신세계그룹', '오프라인 리테일, F&B, 호텔·서비스, 리테일테크까지 다양한 산업 영역을 한 과정에서 경험할 수 있는 교육 과정. 우수 교육생은 상위 5% 채용, 차상위 10% 서류전형 면제(이마트, 조선호텔앤리조트, 신세계푸드, 신세계아이앤씨) 혜택 제공. 교육비 전액(중식 포함) 및 교육지원금(50만원/월) 지급, 합숙 취업캠프·진로 멘토링·기업 설명회 등 취업 지원 프로그램 운영.', 500000, 'https://futurendreamacademy.com/', 15, 34, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-08-18', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[2기] 2026.06.18(목) ~ 2026.08.18.(화), 17시까지', NULL, NULL, NULL, NULL, NULL, NULL, 'support_fund', 'activity_participation_support'),
('Merck International Graduate Fellowship', 'Merck', '카이스트 대학원생 장학금 모집으로, 분야는 Next Generation Biology와 Sustainability 두 가지이며 각 분야별 2명을 모집(작년 대비 정원 2배 확대). 저년차 대상으로 성과중심이 아닌 잠재력 위주로 평가하여 장학생을 선발할 예정.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, '저년차 대상', NULL, NULL, 'general', NULL, NULL, NULL, NULL, '분야별 2명, 총 4명', '지원 기한은 7월 20일까지', NULL, NULL, 'post_undergrad', NULL, NULL, NULL, 'school_external', 'private_foundation');
