-- 한남대학교 장학금 — 하네스 자동 수집 초안 (2026-08-16)
-- 사람 리뷰 후 이 내용을 supabase/data_hannam.sql로 옮길 것.
-- 실제 DB 반영은 지금처럼 supabase/tools/run_sql.py를 사람이 직접 실행함 — 이 파일은 초안임.
-- needs_review로 플래그된 필드가 있는 행은 같은 이름의 harness_review_*.md에서 근거를 먼저 확인할 것.

INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, required_disability_type, foreigner_eligibility, language_test_type, language_test_min_score, required_special_status, required_special_status_all, excluded_special_status, application_deadline, grade_level, major, excluded_major, admission_track, affiliated_institution, min_credits, min_credits_last_semester, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('사립학교교직원연금공단 국고학자금대여', '사립학교교직원연금공단', '2026학년도 2학기 국고학자금대여 신청 안내 (국고학자금 신청 매뉴얼 첨부)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '한남대학교', NULL, NULL, NULL, NULL, NULL, 'school_external', NULL),
('2026년 하반기 군산시 대학생 학자금 이자 지원', '군산시', '', NULL, NULL, NULL, NULL, NULL, '군산시', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-09-04', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~9/4', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'local_gov'),
('2026년도 세종이도인재장학금', NULL, '2026년도 세종이도인재장학금 장학생 선발계획 공고 - 자세한 내용은 첨부파일(선발계획 공고.pdf, 별지 서식 제출 서류.hwp) 참고', NULL, NULL, NULL, NULL, NULL, '세종', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-09-30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~9/30', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'local_gov'),
('2026-2학기 국가근로장학생(취업연계유형)', '한남대학교', '본 명단은 2026-2학기 국가근로장학생(취업연계유형) 최종 선발자 명단입니다. 선발결과를 확인한 후, 기업 담당자와 유선 연락하여 근로시작일 및 근로시간 관련 면담을 요청하시기 바랍니다. 2026-2학기 근로기간은 2026. 9. 1.(화) ~ 2027. 2. 28.(일)입니다. 오픈채팅방 및 사전교육은 최종 선발자에게 개별 안내될 예정입니다.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '한남대학교', NULL, NULL, NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('2026학년도 2학기 주거안정장학금 2차 신청', '한국장학재단', '2026학년도 2학기 주거안정장학금 2차 신청 안내 공지. 신청 매뉴얼 첨부파일(홈페이지/모바일용) 제공.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-09-09', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~9/9', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('2026-2학기 국가장학금 2차 신청', '한국장학재단', '2026년 2학기 국가장학금 2차 신청기간 안내 공지이며, 신청매뉴얼(홈페이지/모바일앱)이 첨부되어 있음', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-09-09', NULL, NULL, NULL, 'general', NULL, NULL, NULL, NULL, NULL, '~9/9', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('2026년 2학기 2차 국가근로장학금', '한국장학재단', '2026학년도 2학기 국가근로장학금 2차 학생 신청기간 안내. 2026년 동계방학 집중근로 프로그램에 참여하고자 하는 학생은 반드시 2차 국가근로장학금을 신청해야 하며, 신(편)입생은 소속대학이 확정된 경우만 신청 가능. 봉사유형 및 취업연계유형 상시신청은 2차 신청기간 종료 후인 2026.9.10.(목)부터 가능.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-09-09', '신(편)입생은 소속대학이 확정된 경우만 신청 가능', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026. 8. 12.(수) 09:00 ~ 9. 9.(수) 18:00', NULL, NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('2026년 하반기 울산광역시 대학생 학자금대출 이자지원 사업', '울산광역시', '', NULL, NULL, NULL, NULL, NULL, '울산광역시', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-08-30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~8/30, 18:00', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'local_gov'),
('2026년 대한민국 인재상 선발', NULL, '2026년 대한민국 인재상 선발 안내 (첨부파일: 2026년 대한민국 인재상 선발 공고문.pdf 참고)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-08-19', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~8/19, 18:00', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', NULL),
('2026-2학기 국가근로장학생(취업연계유형)', '한남대학교', '2026-2학기 국가근로장학생(취업연계유형) 면담대상자 명단 공지. 서류심사 합격자에 한하여 기관에서 학생에게 직접 연락하여 개별 면담을 진행하며, 면담기간은 2026.8.10.(월)~8.11.(화) 18:00까지임. 서류심사 합격자는 최종 선발자가 아니며 기관의 면담 결과와 선발 가능 인원에 따라 최종 선발되지 않을 수 있음.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '한남대학교', NULL, NULL, NULL, NULL, NULL, 'support_fund', 'activity_participation_support'),
('2026-2학기 청소근로장학생 모집', '한남대학교', '근로신청서는 1회만 제출할 수 있으며, 근로지는 우선선발 대상자를 먼저 배정한 후 그 외 신청자를 대상으로 성적이 높은 순으로 배정함. 선발 및 배정 상황에 따라 최종 선발되지 않을 수 있음', NULL, 'https://forms.gle/ChSdiFStXvVpsznf9', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-08-09', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '한남대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('2026-2학기 교내봉사장학생 모집', '한남대학교', '근로신청서는 1회만 제출할 수 있으며, 1지망~3지망 내 동일한 근로지를 중복 신청한 경우 선발 대상에서 제외됩니다. 근로지는 희망근로지별 신청자 중 성적 고득점자 순으로 배정합니다. 선발 및 배정 상황에 따라 최종 선발되지 않을 수 있습니다.', NULL, 'https://forms.gle/1qCtD7eD5iwNMcz19', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-08-09', NULL, NULL, NULL, 'general', NULL, NULL, NULL, NULL, NULL, NULL, '한남대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('2026년 하반기 서울인재대학장학금', NULL, '2026년 하반기 서울인재대학장학금 장학생 선발 안내 공고. 첨부파일에 세부 내용 포함.', NULL, NULL, NULL, NULL, NULL, '서울', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-08-10', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~8/10, 15:00', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'local_gov'),
('2026-2학기 국가근로장학생(취업연계유형) 모집', '한남대학교', '국가근로장학생(취업연계유형) 모집. 근로신청서는 1회만 제출 가능하며, 1지망~2지망 내 동일한 근로지를 중복 신청한 경우 선발 대상에서 제외됨. 1지망, 2지망 자기소개서 별도 제출.', NULL, 'https://forms.gle/KrCW47uDCdzLyq458', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-08-03', NULL, NULL, NULL, 'general', NULL, '직전학기(2026-1학기) 12학점 이상 이수 및 성적 백분율 70점 이상 충족자', 12, NULL, NULL, '~ 08/03 23:59 (기간 연장, 제출기한: 2026. 8. 2.(일) 23:59까지)', '한남대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('2026년 화성시인재육성재단 코나아이 소상공인 장학금', '화성시인재육성재단', '', NULL, NULL, NULL, NULL, NULL, '화성시', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-08-11', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~8/11, 17:00', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'local_gov'),
('2026-2학기 국가근로장학생(일반교내/교외) 모집', '한남대학교', '국가근로장학생(일반교내/교외)을 모집하는 안내로, 근로신청서는 1회만 제출 가능하며 1지망~3지망 내 동일 근로지 중복 신청 시 선발 대상에서 제외된다. 근로지는 소득구간 점수와 성적 환산점수를 합산한 고득점자 순으로 배정된다.', NULL, 'https://forms.gle/GfyxEgykVMnD1x739', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-08-03', NULL, NULL, NULL, 'general', NULL, NULL, NULL, NULL, NULL, '~ 08/03 23:59 (기간 연장)', '한남대학교', NULL, NULL, NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('2026년 정읍시민장학재단 우수인재 장학금', '정읍시민장학재단', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-07-27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~7/27, 18:00', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'private_foundation'),
('2026-2학기 인문100년, 예술체육비전 2+2 중간평가대상자 및 진도보고서 한국장학재단 제출 안내', '한국장학재단', '인문100년, 예술체육비전 2+2 중간평가대상자 및 진도보고서 제출대상자는 기간 내 한국장학재단 온라인신청을 완료해야 하며, 학생보고서 제출 및 신청완료 후 심사를 통과한 학생에 한하여 2026-2학기 등록금 고지서 우선감면 예정. 학생 미신청시 심사 불가 및 탈락처리. 인문100년, 예술체육비전 장학금은 수혜 후 등록휴학 불가하며 2026-2학기 휴학예정자는 반드시 미등록 휴학해야 함.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-08-03', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '제출기한 : 2026.08.03.(월), 한국장학재단 제출 및 온라인 신청은 7월 30일 이후부터 가능', '한남대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('2026-1학기 하계방학 대체근로장학생 재선발', '한남대학교', '2026-1학기 하계방학 대체근로장학생 1차 선발 결과 당시 기관 면담 탈락학생 및 예비번호 학생을 대상으로 한 재선발 면담대상자 명단 안내. 근로지는 소득구간 및 성적 환산점수를 합산한 점수가 높은 순으로 배정되므로 희망한 1~3지망이 아닌 다른 근로지로 배정될 수 있음. 면담기간 내 배정받은 부서/기관과 별도의 면담 진행이 없을 경우 최종 탈락 및 근로 포기로 간주함.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '재선발 대체근로 면담기간 : 2026. 7. 9.(목) 11:00까지', '한남대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'support_fund', 'activity_participation_support'),
('성적우수장학생 선발 기준 안내', '한남대학교', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '한남대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('2027학년도 한국소아당뇨인협회 소아청소년 당뇨인 푸른빛 희망 장학금', '한국소아당뇨인협회', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ARRAY['severe_illness_or_injury'], '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~9/11', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'private_foundation'),
('2026년도 세종이도인재장학금', '세종특별자치시', '', NULL, NULL, NULL, NULL, NULL, '세종', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~7/10, ~9/30', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'local_gov'),
('2026-1학기 주거안정장학금 대학 우선지원 기준 및 지원제외 기준', '한국장학재단', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('2026년 미래이음 장학금', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~7/15', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', NULL),
('2026-1학기 하계방학 대체근로장학생 (국가근로장학사업)', '한남대학교', '본 신청은 2026-1학기 하계방학 대체근로장학생 1차 선발 결과 당시 기관 면담 탈락학생 및 예비번호 학생만을 대상으로 함. 근로지는 소득구간 및 성적 환산점수를 합산한 점수가 높은 순으로 배정되므로, 희망한 1~2지망이 아닌 다른 근로지로 배정될 수 있음. 해당 대상이 아닌 학생이 신청할 경우 별도 안내 없이 탈락 처리됨.', NULL, 'https://forms.gle/tWGijWQdVjmF53Ex9', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-07-05', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~ 07/05 23:59', '한남대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('2026-1학기 주거안정장학금 6월 지급요청서 작성 및 지급일정 관련 안내', '한국장학재단', '2026-1학기 주거안정장학금 6월 지급요청서 작성 및 지급일정 관련 안내 공지. 지출항목별 소명 서류 기준 및 지급요청서 작성 매뉴얼 첨부.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-07-12', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~7/12', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('2026학년도 2학기 한국농어촌희망재단 청년창업농장학생', '한국농어촌희망재단', '2026학년도 2학기 한국농어촌희망재단 청년창업농장학생 신청 접수기간 변경 안내 공지. 세부 선발 안내는 첨부파일(붙임3. 2026년 청년창업농장학금 선발안내.pdf) 참고.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-07-06', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~7/6', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'private_foundation'),
('농촌출신대학생 학자금융자', '한남대학교', '2026-2학기 농촌출신대학생 학자금대출 신청 및 실행 매뉴얼 첨부', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ARRAY['rural_student'], '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '한남대학교', NULL, NULL, NULL, NULL, NULL, 'school_external', NULL),
('2026년 2학기 청년창업농장학금', '농림축산식품부', '등록금 전액 지원, 학업장려금 학기당 250만 원 지원, 최대 7개 학기 지원 가능, 농식품 분야 취·창업 교육 지원, 우수 장학생 해외연수 지원. 영농뿐 아니라 농식품 분야 기업 취업, 국책연구기관 계약직·연구보조원, 대학 연구실 연구원 등 다양한 방식으로 의무종사 이행이 가능하며, 대학원 진학 시 유예가 가능하고 대학원 재학 중 연구활동 및 취업 등을 통해 의무종사를 병행할 수 있음', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-06-30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026. 6. 1.(월) ~ 6. 30.(화) 17:00', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('2026년도 대학생 청소년교육지원사업 멘토 추가 2차 모집', '한남대학교', '대청교(대학생 청소년교육지원사업) 멘토 추가 2차 모집. 구글폼 제출 완료해야 신청 인정되며, 근로 가능 시간은 예산 상황에 따라 추후 조정될 수 있음.', NULL, 'https://forms.gle/GrKie3qzt7faM6f86', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', '2026-06-30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '~ 06/30 17:00까지', '한남대학교', NULL, NULL, NULL, NULL, NULL, 'support_fund', 'activity_participation_support'),
('2026-1학기 하계방학 대체근로장학생 (국가근로장학사업)', '한남대학교', '2026-1학기 하계방학 대체근로장학생 면담대상자 명단 안내 공지. 근로지는 소득구간 및 성적 환산점수를 합산한 점수가 높은 순으로 배정되며, 희망한 1~3지망이 아닌 다른 근로지로 배정될 수 있음. 면담기간 내 면담이 없으면 최종 탈락 및 근로 포기로 간주. 기관 면담 후 탈락한 학생은 재배정 대상자로 분류되어 예비명단 학생과 함께 추가 선발 대상에 포함됨.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '대체근로 면담기간 : 2026. 6. 24.(수) ~ 6. 30.(화) 14:00까지', '한남대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'support_fund', 'activity_participation_support'),
('2026-1학기 하계방학 정기재물조사 근로장학생 면담대상자 안내', '한남대학교', '2026-1학기 하계방학 정기재물조사 근로장학생 면담대상자 명단 공지. 하계방학 정기재물조사 근로기간은 2026.7.6.(월)~8.21.(금)이며 단기근로로 운영되어 중도 포기가 불가능함. 명단 확인 후 근로지 담당자와 유선 연락하여 면담을 요청해야 함.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '한남대학교', NULL, NULL, NULL, NULL, NULL, 'support_fund', 'activity_participation_support');
